theme: blowfish
baseUrl: /
defaultContentLanguage: en

enableInlineShortcodes: true
enableRobotsTXT: true
paginate: 5
summaryLength: 30
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai


taxonomies:
  tag: tags
  category: categories
  author: authors
