languageCode: en-us
languageName: English
displayName: EN
isoCode: en
weight: 1
rtl: false
title: Welcome to the jungle
description: A collection of opinions on engineering, people and life in general
copyright: No rights reserved
dateFormat: January 2, 2006

author:
  name: Welcome to the jungle
  image: img/lion.png
  headline: Opinions on engineering, people and life in general
