languageCode: en-us
languageName: English
displayName: EN
isoCode: en
weight: 1
rtl: false
title: Welcome to the jungle
description: Welcome to the jungle
copyright: No rights reserved
dateFormat: January 2, 2006

author:
  name: Welcome to the jungle
  image: img/lion.png
  headline: Opinions on technology, finance, work and life in general
