---
main:
  - name: All Articles
    identifier: allarticles
    pageRef: blog
    weight: 1
  - name: Analytics
    pageRef: blog
    weight: 1
    parent: allarticles
  - name: Engagement
    pageRef: blog
    weight: 2
    parent: allarticles

subnavigation:
  - name: Engineering
    pageRef: categories/engineering
    weight: 1
  - name: Leadership
    pageRef: tags/leadership
    weight: 2
  - name: Technology
    pageRef: categories/technology
    weight: 3
  - name: Web3
    pageRef: tags/web3
    weight: 4
