---
main:
  - name: All Articles
    pageRef: blog
    weight: 1

subnavigation:
  - name: Engineering
    pageRef: categories/engineering
    weight: 1
  - name: Leadership
    pageRef: tags/leadership
    weight: 2
  - name: Technology
    pageRef: categories/technology
    weight: 3
  - name: Web3
    pageRef: tags/web3
    weight: 4
