---
colorScheme: noir
logo: img/logo.png

enableSearch: true

keywords:
  - Engineering
  - Software Development
  - Tech
  - Web3
  - Crypto
  - Nft

list:
  showSummary: true

article:
  showHero: true
  heroStyle: big
  layoutBackgroundBlur: true
  showViews: false
  showSummary: true
  sharingLinks: false
  showAuthorsBadges: true
  showTaxonomies: false
  showTableOfContents: true
  showEdit: false
  showAuthor: false
  showAuthorsBadges: false

homepage:
  layout: profile
  showRecent: true
  showRecentItems: 10
  showMoreLink: true
  showMoreLinkDest: /blog

taxonomy:
  showSummary: true

term:
  showSummary: true
  showHero: true
  heroStyle: basic

header:
  layout: basic
  showAppearanceSwitcher: true
