---
colorScheme: noir

enableSearch: true

list:
  showSummary: true

article:
  showViews: false
  showSummary: true
  sharingLinks: false
  showAuthorsBadges: true
  showTaxonomies: true
  showTableOfContents: true
  showEdit: false
  showAuthor: false

homepage:
  layout: background
  homepageImage: img/jungle.jpg
  showRecent: true
  showRecentItems: 5
  showMoreLink: true
  showMoreLinkDest: /blog
