---
colorScheme: noir

enableSearch: true
defaultBackgroundImage: img/jungle.jpg

list:
  showSummary: true
  showHero: true
  heroStyle: background

article:
  showHero: true
  heroStyle: background
  layoutBackgroundBlur: true
  showViews: false
  showSummary: true
  sharingLinks: false
  showAuthorsBadges: true
  showTaxonomies: true
  showTableOfContents: true
  showEdit: false
  showAuthor: false

homepage:
  layout: background
  showRecent: true
  showRecentItems: 10
  showMoreLink: true
  showMoreLinkDest: /blog

taxonomy:
  showSummary: true
  showHero: true
  heroStyle: background

term:
  showSummary: true
  showHero: true
  heroStyle: background

header:
  layout: fixed
