---
colorScheme: noir

enableSearch: true

list:
  showSummary: true

article:
  showHero: true
  heroStyle: big

  layoutBackgroundBlur: true
  showViews: false
  showSummary: true
  sharingLinks: false
  showAuthorsBadges: true
  showTaxonomies: true
  showTableOfContents: true
  showEdit: false
  showAuthor: false

homepage:
  layout: page
  showRecent: true
  showRecentItems: 10
  showMoreLink: true
  showMoreLinkDest: /blog

taxonomy:
  showSummary: true

term:
  showSummary: true

header:
  layout: basic
